# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: saiyam1814.github.io
baseurl: 
title: 
author: Saiyam Pathak
description: 
avatar: /assets/images/saiyam.jpg 
email: 
github: # username
twitter: 
linkedin:
stackoverflow:   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: 
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
